<?php /* Smarty version Smarty-3.1-DEV, created on 2013-10-09 16:55:04
         compiled from "/var/www/html/wordpress/tiki/templates/admin/include_rss.tpl" */ ?>
<?php /*%%SmartyHeaderCode:147227359552558a68ee3fa4-60425184%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '3418acc6b378504eb4283c10c2334e3aa54f9579' => 
    array (
      0 => '/var/www/html/wordpress/tiki/templates/admin/include_rss.tpl',
      1 => 1369161873,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '147227359552558a68ee3fa4-60425184',
  'function' => 
  array (
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1-DEV',
  'unifunc' => 'content_52558a691dd210_59724896',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_52558a691dd210_59724896')) {function content_52558a691dd210_59724896($_smarty_tpl) {?><?php if (!is_callable('smarty_block_remarksbox')) include 'lib/smarty_tiki/block.remarksbox.php';
if (!is_callable('smarty_block_tabset')) include 'lib/smarty_tiki/block.tabset.php';
if (!is_callable('smarty_block_tab')) include 'lib/smarty_tiki/block.tab.php';
if (!is_callable('smarty_function_preference')) include 'lib/smarty_tiki/function.preference.php';
if (!is_callable('smarty_function_icon')) include 'lib/smarty_tiki/function.icon.php';
?><?php $_smarty_tpl->smarty->_tag_stack[] = array('remarksbox', array('type'=>"tip",'title'=>"Tip")); $_block_repeat=true; echo smarty_block_remarksbox(array('type'=>"tip",'title'=>"Tip"), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>

	Use this page to configure the feeds generated by Tiki. To syndicate feeds from other sites, use the <strong>Admin</strong> &gt; <strong>External Feeds</strong> menu option, or <a class="rbox-link" href="tiki-admin_rssmodules.php" title="External feeds">Click Here</a>.
<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_remarksbox(array('type'=>"tip",'title'=>"Tip"), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>


<form action="tiki-admin.php?page=rss" method="post">
	<input type="hidden" name="rss" />
	<div class="heading input_submit_container" style="text-align: right">
		<input type="submit" value="Change preferences" />
	</div>

	<?php $_smarty_tpl->smarty->_tag_stack[] = array('tabset', array('name'=>"admin_rss")); $_block_repeat=true; echo smarty_block_tabset(array('name'=>"admin_rss"), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>

		<?php $_smarty_tpl->smarty->_tag_stack[] = array('tab', array('name'=>"General Preferences")); $_block_repeat=true; echo smarty_block_tab(array('name'=>"General Preferences"), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>

			<?php echo smarty_function_preference(array('name'=>'feed_default_version'),$_smarty_tpl);?>

			<div class="adminoptionboxchild feed_default_version_childcontainer 5">
				<?php echo smarty_function_preference(array('name'=>'feed_atom_author_name'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_atom_author_email'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_atom_author_url'),$_smarty_tpl);?>

			</div>
			<div class="adminoptionboxchild feed_default_version_childcontainer 2">
				<?php echo smarty_function_preference(array('name'=>'feed_rss_editor_email'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_rss_webmaster_email'),$_smarty_tpl);?>

			</div>

			<?php echo smarty_function_preference(array('name'=>'feed_img'),$_smarty_tpl);?>

			<?php echo smarty_function_preference(array('name'=>'feed_language'),$_smarty_tpl);?>

			<?php echo smarty_function_preference(array('name'=>'feed_cache_time'),$_smarty_tpl);?>


			<?php echo smarty_function_preference(array('name'=>'feed_basic_auth'),$_smarty_tpl);?>

		<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_tab(array('name'=>"General Preferences"), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>


		<?php $_smarty_tpl->smarty->_tag_stack[] = array('tab', array('name'=>"Feeds")); $_block_repeat=true; echo smarty_block_tab(array('name'=>"Feeds"), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>

			<?php echo smarty_function_preference(array('name'=>'feed_articles'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_articles_childcontainer">
				<a href="tiki-articles_rss.php" title="Feed for articles"> <?php echo smarty_function_icon(array('_id'=>'feed'),$_smarty_tpl);?>
</a>
				<?php echo smarty_function_preference(array('name'=>'feed_articles_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_articles_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_articles_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_articles_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_articles_homepage'),$_smarty_tpl);?>

			</div>

			<?php echo smarty_function_preference(array('name'=>'feed_blogs'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_blogs_childcontainer">
				<a href="tiki-blogs_rss.php" title="Feed for blogs"> <?php echo smarty_function_icon(array('_id'=>'feed'),$_smarty_tpl);?>
</a>
				<?php echo smarty_function_preference(array('name'=>'feed_blogs_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_blogs_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_blogs_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_blogs_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_blogs_homepage'),$_smarty_tpl);?>

			</div>

			<?php echo smarty_function_preference(array('name'=>'feed_blog'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_blog_childcontainer">
				<a href="tiki-list_blogs.php" title="Feed for individual blogs"> <?php echo smarty_function_icon(array('_id'=>'feed'),$_smarty_tpl);?>
</a>
				<?php echo smarty_function_preference(array('name'=>'feed_blog_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_blog_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_blog_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_blog_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_blog_homepage'),$_smarty_tpl);?>

			</div>

			<?php echo smarty_function_preference(array('name'=>'feed_image_galleries'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_image_galleries_childcontainer">
				<a href="tiki-image_galleries_rss.php" title="Feed for image galleries"> <?php echo smarty_function_icon(array('_id'=>'feed'),$_smarty_tpl);?>
</a>
				<?php echo smarty_function_preference(array('name'=>'feed_image_galleries_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_image_galleries_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_image_galleries_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_image_galleries_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_image_galleries_homepage'),$_smarty_tpl);?>

			</div>

			<?php echo smarty_function_preference(array('name'=>'feed_image_gallery'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_image_gallery_childcontainer">
				<a href="tiki-galleries.php" title="Feed for individual image galleries"> <?php echo smarty_function_icon(array('_id'=>'feed'),$_smarty_tpl);?>
</a>
				<?php echo smarty_function_preference(array('name'=>'feed_image_gallery_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_image_gallery_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_image_gallery_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_image_gallery_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_image_gallery_homepage'),$_smarty_tpl);?>

			</div>

			<?php echo smarty_function_preference(array('name'=>'feed_file_galleries'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_file_galleries_childcontainer">
				<a href="tiki-file_galleries_rss.php" title="Feed for file galleries"> <?php echo smarty_function_icon(array('_id'=>'feed'),$_smarty_tpl);?>
</a>
				<?php echo smarty_function_preference(array('name'=>'feed_file_galleries_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_file_galleries_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_file_galleries_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_file_galleries_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_file_galleries_homepage'),$_smarty_tpl);?>

			</div>

			<?php echo smarty_function_preference(array('name'=>'feed_file_gallery'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_file_gallery_childcontainer">
				<a href="tiki-list_file_gallery.php" title="Feed for individual file galleries"> <?php echo smarty_function_icon(array('_id'=>'feed'),$_smarty_tpl);?>
</a>
				<?php echo smarty_function_preference(array('name'=>'feed_file_gallery_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_file_gallery_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_file_gallery_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_file_gallery_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_file_gallery_homepage'),$_smarty_tpl);?>

			</div>

			<?php echo smarty_function_preference(array('name'=>'feed_wiki'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_wiki_childcontainer">
				<a href="tiki-wiki_rss.php" title="Feed for wiki pages (with diff)"> <?php echo smarty_function_icon(array('_id'=>'feed'),$_smarty_tpl);?>
</a>
				<a href="tiki-wiki_rss_no_diff.php" title="Feed for wiki pages (no diff)"> <?php echo smarty_function_icon(array('_id'=>'feed'),$_smarty_tpl);?>
</a>
				<?php echo smarty_function_preference(array('name'=>'feed_wiki_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_wiki_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_wiki_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_wiki_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_wiki_homepage'),$_smarty_tpl);?>

			</div>

			<?php echo smarty_function_preference(array('name'=>'feed_forums'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_forums_childcontainer">
				<a href="tiki-forums_rss.php" title="Feed for forums"> <?php echo smarty_function_icon(array('_id'=>'feed'),$_smarty_tpl);?>
</a>
				<?php echo smarty_function_preference(array('name'=>'feed_forums_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_forums_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_forums_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_forums_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_forums_homepage'),$_smarty_tpl);?>

			</div>
			
			<?php echo smarty_function_preference(array('name'=>'feed_forum'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_forum_childcontainer">
				<a href="tiki-forums.php" title="Feed for individual forums"> <?php echo smarty_function_icon(array('_id'=>'feed'),$_smarty_tpl);?>
</a>
				<?php echo smarty_function_preference(array('name'=>'feed_forum_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_forum_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_forum_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_forum_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_forum_homepage'),$_smarty_tpl);?>

			</div>

			<?php echo smarty_function_preference(array('name'=>'feed_tracker'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_tracker_childcontainer">
				<a href="tiki-list_trackers.php" title="Feed for trackers"> <?php echo smarty_function_icon(array('_id'=>'feed'),$_smarty_tpl);?>
</a>
				<?php echo smarty_function_preference(array('name'=>'feed_tracker_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_tracker_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_tracker_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_tracker_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_tracker_homepage'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_tracker_labels'),$_smarty_tpl);?>

			</div>

			<?php echo smarty_function_preference(array('name'=>'feed_calendar'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_calendar_childcontainer">
				<a href="tiki-calendars_rss.php" title="Feed for calendars"> <?php echo smarty_function_icon(array('_id'=>'feed'),$_smarty_tpl);?>
</a>
				<?php echo smarty_function_preference(array('name'=>'feed_calendar_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_calendar_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_calendar_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_calendar_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_calendar_homepage'),$_smarty_tpl);?>

			</div>
			
			<?php echo smarty_function_preference(array('name'=>'feed_directories'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_directories_childcontainer">
				<a href="tiki-directories_rss.php" title="Feed for directories"> <?php echo smarty_function_icon(array('_id'=>'feed'),$_smarty_tpl);?>
</a>
				<?php echo smarty_function_preference(array('name'=>'feed_directories_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_directories_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_directories_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_directories_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_directories_homepage'),$_smarty_tpl);?>

			</div>

			<?php echo smarty_function_preference(array('name'=>'feed_shoutbox'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_shoutbox_childcontainer">
				<a href="tiki-shoutbox_rss.php" title="Feed for shoutbox"> <?php echo smarty_function_icon(array('_id'=>'feed'),$_smarty_tpl);?>
</a>
				<?php echo smarty_function_preference(array('name'=>'feed_shoutbox_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_shoutbox_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_shoutbox_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_shoutbox_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_shoutbox_homepage'),$_smarty_tpl);?>

			</div>
		<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_tab(array('name'=>"Feeds"), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>

	<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_tabset(array('name'=>"admin_rss"), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>


	<div class="heading input_submit_container" style="text-align: center">
		<input type="submit" value="Change preferences" />
	</div>
</form>
<?php }} ?>